version: "3.8"

services:
  dev:
    container_name: manage-my-time
    build:
      context: ..
      target: development
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    restart: unless-stopped